### ISSUE TITLE
Improve description in README.md

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io-release#29]

**Comment by gastaldi** [comment]
Not in the README, in the GitHub repository. It reads `Manage code.quarku.io releases`

**Comment by gastaldi** [comment]
Btw a README with links to the CI and the staging and production environments would be great to have

**Comment by ia3andy** [comment]
> README with links to the CI and the staging and production environments would be great to have

@gastaldi those have restricted access :-/

> Not in the README, in the GitHub repository. It reads Manage code.quarku.io releases

Do you have an idea of what else to say in the GH description? This seem pretty clear to me :)

**Comment by gastaldi** [comment]
It's fine to have restricted access, it would be only visited by people with access to the environment :)

There is a missing `s` in the URL

**Comment by ia3andy** [comment]
@gastaldi would u help making the readme with info on:
- Where are the CI:
https://ci.ext.devshift.net/view/code-quarkus/
- Where are the envs:
https://console.app-sre-stage.openshift.com/console/project/code-quarkus-stage/overview
https://console.app-sre.openshift.com/console/project/code-quarkus-production/overview
- How to request access
- How to promote a new version to production

That would be great!!

**Comment by ia3andy** [comment]
An issue has been opened in APP-SRE to use our own CI to build/push the image.
The release to production (CD) would still be in APP-SRE.
